#
# Copyright © 2016-2024 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Push Docker Image

on:
  workflow_dispatch:  # Allows manual execution

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Download Docker Image Artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
        path: .

    - name: Load Docker Image
      run: docker load -i image.tar

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push 5giotlead/tb-ce:3.9.1
